Added TrustServerCertificate param in connectionInfo
Canner/WrenAI pull request #746
Opened 2024-10-09 18:40 UTC by himanshu634

Added TrustServerCertificate param in connectionInfo as described [here](https://github.com/Canner/WrenAI/issues/698).

2024-10-11 06:50 UTC, himanshu634 commented
@wwwy3y3 @grieve54706  It is ready to review !

2024-10-15 08:27 UTC, grieve54706 requested changes
It should not be hard-coded. It should be an option on the website that lets users decide whether their database needs this.

2024-10-15 09:17 UTC, himanshu634 commented
I already doubted it. Anyways, I will do it.

2024-10-21 16:29 UTC, himanshu634 commented
@grieve54706 Please review it!, I have added Enable Trust Server Certificate user side as well.

2024-10-22 08:56 UTC, wwwy3y3 commented
@andreashimin will help review

2024-10-22 10:25 UTC, andreashimin reviewed
Hi @himanshu634, I saw there is a conflict in this PR,
Could you help rebase it? Thank you

2024-10-22 10:25 UTC, andreashimin commented on wren-ui/src/apollo/server/dataSource.ts
> +        },
According to #698, you need to convert it to string `YES`
if false then don't provide the property

2024-10-22 10:25 UTC, andreashimin commented on wren-ui/src/components/pages/setup/dataSources/SQLServerProperties.tsx
> +      </Form.Item>
Please help make adjustment to the property
- Default to checked
- Add `extra` prop to `Form.Item` with value: `This parameter is used to skip server certificate validation. If you are using a trusted certificate, you can disable it.`

2024-10-22 13:10 UTC, himanshu634 commented
@andreashimin Please check now, thanks.

2024-10-23 02:37 UTC, andreashimin approved these changes
LGTM

2024-10-23 02:38 UTC, merged

2024-10-23 02:39 UTC, andreashimin commented
Hi @himanshu634 ,

Thank you for your contribution 👍🏼 
You can now DM @chilijung on Discord with https://github.com/Canner/WrenAI/issues/698 to get the swag form link.